all:
	g++ -fpermissive -std=c++11 main.cpp menu.cpp hamming.cpp prevent-close.cpp

g:
	g++ -fpermissive -std=c++11 main.cpp menu.cpp hamming.cpp prevent-close.cpp -g

run:
	stty -ixon && ./a.out

.PHONY: all g run
